# Numpy Array operations

In [2]:
import numpy as np

In [5]:
arr = np.arange(11)
print("Basic Slicing: ", arr[2:7])
print("With Steps: ", arr[1:8:2])
print("negative indexing: ", arr[-2])

Basic Slicing:  [2 3 4 5 6]
With Steps:  [1 3 5 7]
negative indexing:  9


In [8]:
arr_2d = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])
print("Specific element", arr_2d[1, 2])
print("Entire row: ", arr_2d[1])
print("Entire column: ", arr_2d[:, 1])

Specific element 6
Entire row:  [4 5 6]
Entire column:  [2 5 8]


### Sorting


In [14]:
unsorted = np.array([3, 1, 4, 1, 5, 9, 2, 6])
print("Sorted Array", np.sort(unsorted))

arr_2d_unsorted = np.array([[4, 9], [1, 2], [3, 2]])
print("Sorted 2D array by column", np.sort(arr_2d_unsorted, axis=0))
print("Sorted 2D array by row", np.sort(arr_2d_unsorted, axis=1))

Sorted Array [1 1 2 3 4 5 6 9]
Sorted 2D array by column [[1 2]
 [3 2]
 [4 9]]
Sorted 2D array by row [[4 9]
 [1 2]
 [2 3]]


### Filters

In [4]:
numbers = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
even_number = numbers[numbers % 2 == 0]
print("Even numbers", even_number)

Even numbers [ 2  4  6  8 10]


### With Mask

In [6]:
numbers = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
mask = numbers % 2 == 0

print("Mask:", mask)
even_numbers = numbers[mask]
print("Even numbers:", even_numbers)


Mask: [False  True False  True False  True False  True False  True]
Even numbers: [ 2  4  6  8 10]


### Fancy indexing vs np.where()

In [8]:
numbers = np.array([1,2,3,4,5,6,7,8,9,10])

# --- Fancy Indexing ---
indices = [0, 2, 4]
print("Fancy indices:", indices)
print("Fancy result:", numbers[indices])


# --- Boolean mask ---
mask = numbers > 5
print("\nMask:", mask)

# --- np.where ---
where_result = np.where(mask)
print("\nnp.where result (indices):", where_result)

# Using those indices
print("Using np.where:", numbers[where_result])

# Direct mask indexing
print("Using mask directly:", numbers[mask])

print('original array: ' , numbers)


Fancy indices: [0, 2, 4]
Fancy result: [1 3 5]

Mask: [False False False False False  True  True  True  True  True]

np.where result (indices): (array([5, 6, 7, 8, 9]),)
Using np.where: [ 6  7  8  9 10]
Using mask directly: [ 6  7  8  9 10]
original array:  [ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
condition_array = np.where(numbers > 5, "true",  "false")
print(condition_array)

# If number > 5 → return "true"
# Else → return "false"


['false' 'false' 'false' 'false' 'false' 'true' 'true' 'true' 'true'
 'true']


### for 2D

In [17]:
arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

mask = arr > 5
print("Mask result: \n", mask)

print("Mask Result in arr: \n", arr[mask])

result = arr.copy()
result[mask] = 0
print("mask to modify values: \n", result)

indices = np.where(arr > 5)
print("Indices of condition true: \n",indices) # (row indices, col indices)

labels = np.where(arr > 5, "HIGH", "LOW")
print(labels)





Mask result: 
 [[False False False]
 [False False  True]
 [ True  True  True]]
Mask Result in arr: 
 [6 7 8 9]
mask to modify values: 
 [[1 2 3]
 [4 5 0]
 [0 0 0]]
Indices of condition true: 
 (array([1, 2, 2, 2]), array([2, 0, 1, 2]))
[['LOW' 'LOW' 'LOW']
 ['LOW' 'LOW' 'HIGH']
 ['HIGH' 'HIGH' 'HIGH']]


### Adding and removing data

In [19]:
print("\n================= ORIGINAL 2D ARRAY =================")
arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
print(arr)



# ------------------------------------------------------
# 1. ADDING DATA  
# ------------------------------------------------------

print("\n================= ADDING DATA =================")

# 1.1 Add a row (using np.append)
new_row = np.array([[10, 11, 12]])
arr_add_row = np.append(arr, new_row, axis=0)
print("\nAfter adding a row (append):")
print(arr_add_row)

# 1.2 Add a column (using np.append)
new_column = np.array([[100], [200], [300]])
arr_add_col = np.append(arr, new_column, axis=1)
print("\nAfter adding a column (append):")
print(arr_add_col)

# 1.3 Insert a row at index 1
arr_insert_row = np.insert(arr, 1, [20, 21, 22], axis=0)
print("\nAfter inserting a row at index 1 (insert):")
print(arr_insert_row)

# 1.4 Insert a column at index 2
arr_insert_col = np.insert(arr, 2, [30, 31, 32], axis=1)
print("\nAfter inserting a column at index 2 (insert):")
print(arr_insert_col)

# 1.5 Add rows using vstack
arr_vstack = np.vstack([arr, [13, 14, 15]])
print("\nAfter adding a row (vstack):")
print(arr_vstack)

# 1.6 Add columns using hstack
arr_hstack = np.hstack([arr, [[16], [17], [18]]])
print("\nAfter adding a column (hstack):")
print(arr_hstack)

# 1.7 Concatenate arrays (vertical)
extra_arr = np.array([[50, 60, 70]])
arr_concat_v = np.concatenate((arr, extra_arr), axis=0)
print("\nAfter concatenating vertically:")
print(arr_concat_v)

# 1.8 Concatenate arrays (horizontal)
extra_arr_h = np.array([[100], [200], [300]])
arr_concat_h = np.concatenate((arr, extra_arr_h), axis=1)
print("\nAfter concatenating horizontally:")
print(arr_concat_h)



# ------------------------------------------------------
# 2. REMOVING DATA  
# ------------------------------------------------------

print("\n================= REMOVING DATA =================")

# 2.1 Remove row 1
arr_remove_row = np.delete(arr, 1, axis=0)
print("\nAfter removing row index 1:")
print(arr_remove_row)

# 2.2 Remove column 2
arr_remove_col = np.delete(arr, 2, axis=1)
print("\nAfter removing column index 2:")
print(arr_remove_col)

# 2.3 Remove multiple rows
arr_remove_rows = np.delete(arr, [0, 2], axis=0)
print("\nAfter removing rows 0 and 2:")
print(arr_remove_rows)

# 2.4 Remove multiple columns
arr_remove_cols = np.delete(arr, [0, 2], axis=1)
print("\nAfter removing columns 0 and 2:")
print(arr_remove_cols)



# ------------------------------------------------------
# DONE!
# ------------------------------------------------------

print("\n================= END OF COMPLETE DEMO =================")



================= ORIGINAL 2D ARRAY =================
[[1 2 3]
 [4 5 6]
 [7 8 9]]

================= ADDING DATA =================

After adding a row (append):
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

After adding a column (append):
[[  1   2   3 100]
 [  4   5   6 200]
 [  7   8   9 300]]

After inserting a row at index 1 (insert):
[[ 1  2  3]
 [20 21 22]
 [ 4  5  6]
 [ 7  8  9]]

After inserting a column at index 2 (insert):
[[ 1  2 30  3]
 [ 4  5 31  6]
 [ 7  8 32  9]]

After adding a row (vstack):
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [13 14 15]]

After adding a column (hstack):
[[ 1  2  3 16]
 [ 4  5  6 17]
 [ 7  8  9 18]]

After concatenating vertically:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [50 60 70]]

After concatenating horizontally:
[[  1   2   3 100]
 [  4   5   6 200]
 [  7   8   9 300]]

================= REMOVING DATA =================

After removing row index 1:
[[1 2 3]
 [7 8 9]]

After removing column index 2:
[[1 2]
 [4 5]
 [7 8]]

After removing rows 0 and

In [20]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6, 7])
c = np.array([7, 8, 9])

print("Compatibility shapes", a.shape == b.shape)

Compatibility shapes False
